Repository thoth-station/ansible-role-postgresql, pull requests merged in 2019-09, with the labels that each got.

#1 Provide namespace explictly
  tasks/main.yml
Labels: size/XS

#4 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: approved, size/XS

#3 Generate passowrd without punctation
  tasks/main.yml
Labels: approved, size/XS

#2 Use generated secrets when provisioning the service from Service Catalog
  tasks/main.yml
Labels: approved, size/M

#5 Change default volume capacity
  vars/main.yml
Labels: approved, size/XS

#7 Document default variables used during provisioning
  README.md
Labels: approved, size/S

#8 fix of postgresql_database component
  vars/main.yml
Labels: approved, size/XS
